name: daudio
version: 0.0.1
repository: https://github.com/buggaboo/daudio
description: miniaudio wrapper

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  ffi_tool: ^0.2.5

dev_dependencies:
  test: ^1.0.0

# The minimal configuration for flutter to pick up this package as a flutter-plugin with native dependencies
flutter:
  plugin:
    android:
    ios: